services:
  - type: web
    name: arogya-clinic-be
    env: python
    rootDir: BE
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: NOTIFICATION_EMAILS
        value: "chiranjeevkumar47@gmail.com"
      - key: ENABLE_DB
        value: "True"
      - key: PYTHON_VERSION
        value: "3.12.0"
