import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navigation
    home: "Home",
    about: "About",
    services: "Services",
    appointments: "Book Appointment",
    contact: "Contact",

    // Home Page — Hero
    welcome: "Welcome",
    drName: "Dr. Deepak Kumar",
    tagline: "Your Trusted Healthcare Partner",
    specialty: "MBBS, MD (General Medicine)",
    experience: "15+ Years Experience",
    bookAppointment: "Book Appointment Now",
    viewServices: "View Our Services",
    location: "Muzaffarpur, Bihar",
    heroDesc: "We provide guideline-directed comprehensive care for Diabetes, Blood Pressure, Thyroid, Asthma, COPD, and Abdominal diseases, prioritizing your long-term wellness.",
    education: "Education",
    educationDetail: "MBBS, SKMCH",
    specialization: "Specialization",
    specializationDetail: "MD General medicine, DMCH Darbhanga",

    // Home Page — Why Choose Us
    whyChooseTitle: "Why Choose Our Practice",
    whyChooseDesc: "We combine academic rigour with patient-centric care to ensure you receive the best possible medical outcomes in Muzaffarpur.",
    academicExcellence: "Academic Excellence",
    academicExcellenceDesc: "With foundational training from SKMCH and advanced MD General medicine specialization from DMCH Darbhanga, Dr. Deepak Kumar brings institutional expertise to private practice.",
    patientFirst: "Patient First",
    patientFirstDesc: "Prioritizing listening and empathy. Every treatment plan is tailored to your unique health profile and lifestyle.",
    modernFacility: "Modern Facility",
    modernFacilityDesc: "Equipped with the latest diagnostic tools for accurate assessment and effective management.",
    verifiedExperience: "Verified Experience",
    verifiedExperienceDesc: "A proven track record of successful patient outcomes and a trusted name in the Muzaffarpur medical community.",

    // Home Page — Core Services
    coreServicesTitle: "Core Medical Services",
    coreServicesDesc: "Specialized care across multiple disciplines to support your long-term health journey.",
    generalConsultation: "General Consultation",
    generalConsultationDesc: "Comprehensive health checks and routine wellness management.",
    diagnostics: "Diagnostics",
    diagnosticsDesc: "In-depth laboratory tests and clinical evaluation for precise diagnosis.",
    chronicCare: "Chronic Care",
    chronicCareDesc: "Long-term management strategies for diabetes, hypertension, and more.",
    emergencyAdvice: "Emergency Advice",
    emergencyAdviceDesc: "Critical care guidance and immediate clinical intervention.",
    exploreServices: "Explore all medical services",

    // Home Page — CTA
    ctaTitle: "Take the first step to better health.",
    ctaDesc: "Schedule your appointment today for personalized medical consultation in Muzaffarpur.",
    ctaButton: "Book Appointment Now",
    phone: "9199943818",

    // About Page
    aboutTitle: "About Dr. Deepak Kumar",
    aboutSubtitle: "Dedicated to Excellence in Healthcare",
    aboutDesc: "is a distinguished medical professional dedicated to revolutionizing patient care throughout the Tirhut division. Based in Muzaffarpur, the \"Capital of North Bihar,\" he bridges the gap between advanced medical science and compassionate healing, offering a trusted sanctuary for the community's health.",
    yearsExp: "5+ Years",
    yearsExpDesc: "Of clinical excellence and community service in Bihar.",

    // About Page — Education
    academicFoundation: "Academic Foundation",
    mbbs: "MBBS",
    mbbsCollege: "Sri Krishna Medical College (SKMCH)",
    mbbsDesc: "Completed his foundational medical education at one of Bihar's premier institutions, developing a robust clinical perspective.",
    md: "MD General medicine",
    mdCollege: "Darbhanga Medical College (DMCH Darbhanga)",
    mdDesc: "Specialized training that honed his expertise in diagnostic precision and advanced therapeutic interventions.",
    eliteTraining: "Elite Training",
    eliteTrainingDesc: "Educated at Bihar's most rigorous medical sanctuaries.",

    // About Page — Community
    communityTitle: "A Lifelong Vow to Muzaffarpur",
    communityDesc: "Muzaffarpur is more than just a practice location; it is home. Operating from Arogya Clinic, Dr. Deepak Kumar's commitment extends to the heart of the \"Land of Shahi Lychees\". He is deeply involved in local health initiatives, ensuring that quality healthcare is accessible to every strata of society in Bihar.",
    freeCamps: "Regular free health camps for underprivileged populations.",
    mentorship: "Mentorship programs for local medical aspirants.",
    preventiveHealth: "Primary advocate for preventive health education in rural zones.",

    // About Page — Milestones
    milestonesTitle: "Professional Milestones",
    milestonesDesc: "A legacy of clinical excellence and academic rigor.",
    foundation: "Foundation",
    academicCommencement: "Academic Commencement",
    academicCommencementDesc: "MBBS Graduation from SKMCH, Muzaffarpur.",
    specializationLabel: "Specialization",
    advancedMedicine: "Advanced Medicine",
    advancedMedicineDesc: "Obtained MD General medicine from the prestigious Darbhanga Medical College.",
    establishment: "Establishment",
    civicLeadership: "Civic Leadership",
    civicLeadershipDesc: "Established the landmark clinic in Muzaffarpur focusing on empathetic care.",

    // About Page — Accreditations
    accreditationsTitle: "Accreditations & Honors",
    imaMember: "IMA Member",
    imaDesc: "Indian Medical Association",
    boardCertified: "Board Certified",
    boardDesc: "Medical Council of India",
    excellenceAward: "Excellence Award",
    awardDesc: "State Health Mission",
    fellowship: "Fellowship",
    fellowshipDesc: "Internal Medicine",

    // Services Page
    servicesHeroBadge: "Patient-Centered Excellence",
    servicesHeroTitle: "Specialized Care Tailored to Your Wellness",
    servicesHeroDesc: "Experience comprehensive medical solutions combining state-of-the-art diagnostics with a compassionate, editorial approach to modern healthcare.",
    clinicalServices: "Clinical Services",
    clinicalServicesDesc: "Our multidisciplinary approach ensures every patient receives focused attention and a personalized treatment roadmap.",
    diabetesBp: "Diabetes & Blood Pressure Management",
    diabetesBpDesc: "Guideline-directed medical treatment for managing chronic conditions like Diabetes and Hypertension. We provide continuous monitoring and personalized therapeutic plans to ensure your vitals remain balanced and optimal.",
    learnMore: "Learn More",
    endocrineCare: "Endocrine Care",
    endocrineCareDesc: "Advanced diagnosis and holistic management of Thyroid-related disorders.",
    respiratoryHealth: "Respiratory Health",
    respiratoryHealthDesc: "Specialized interventions for Asthma, COPD, and other pulmonary challenges.",
    abdomenDiseases: "Abdomen Diseases",
    abdomenDiseasesDesc: "Expert consultations and treatment plans for diseases related to the abdomen and GI tract.",
    teleconsultation: "Teleconsultation",
    teleconsultationDesc: "Access personalized medical advice and follow-up care remotely from the comfort of your home.",
    beyondMedicine: "Beyond Medicine: A Partnership in Health",
    evidenceBased: "Evidenced-Based Protocols",
    evidenceBasedDesc: "Treatments rooted in the latest clinical research and global medical standards.",
    personalizedTouch: "Personalized Touch",
    personalizedTouchDesc: "Every patient is unique. We build medical plans that respect individual lifestyles.",
    startRecovery: "Start Your Path to Recovery",
    startRecoveryDesc: "Schedule a comprehensive consultation today and experience healthcare reimagined for the modern age.",
    scheduleAppt: "Schedule Appointment",
    viewPricing: "View Pricing",

    // Appointments Page
    appointmentTitle: "Book Your Appointment",
    clinicLocation: "Clinic Location",
    address: "Saktidharamkata Bada Jagganath, near God Father Public School, 842004",
    phoneNumber: "Phone Number",
    phoneValue: "919994381893",
    operatingHours: "Operating Hours",
    hoursValue: "Morning visit timing 6 am to 9 am\nEvening visit timing 3 pm to 6 pm",
    emailAddress: "Email Address",
    emailValue: "deepakkumar21121995@gmail.com",
    availableToday: "Available Today",
    requestAppointment: "Request an Appointment",
    appointmentRequested: "Appointment Requested!",
    appointmentRequestedMsg: "We've received your request and will contact you shortly to confirm your appointment.",
    submissionFailed: "Submission Failed",
    fullName: "Full Name",
    namePlaceholder: "e.g. Ramesh Kumar",
    phonePlaceholder: "91 00000 00000",
    emailPlaceholder: "your@email.com",
    preferredDate: "Preferred Date",
    preferredTime: "Preferred Time Slot",
    medicalConcern: "Medical Concern",
    concernPlaceholder: "Briefly describe your health concern...",
    sendRequest: "Send Request",
    sending: "Sending...",
    privacyPolicy: "By submitting this form, you agree to our Privacy Policy.",
    bookNow: "Book Appointment",
    confirmation: "Appointment Booked Successfully!",
    confirmationMsg: "You will receive a confirmation call shortly.",
    selectDate: "Select Date",
    selectTime: "Select Time Slot",
    symptoms: "Describe your symptoms",

    // Time Slots
    morningSlot: "Morning (9 AM - 12 PM)",
    afternoonSlot: "Afternoon (2 PM - 5 PM)",
    eveningSlot: "Evening Clinic (8:30 PM Onwards)",
    teleconsultSlot: "Teleconsultation",

    // WhatsApp Button
    whatsappChat: "Chat on WhatsApp",
    whatsappMsg: "Hello Dr. Deepak, I would like to consult with you.",
    available24x7: "Available 24x7",
    instantResponse: "Instant Response",

    // WhatsApp Widget
    reset: "Reset",
    send: "Send",
    sendTo: "Send to",
    yourDetails: "Your details go directly to",
    preConsultForm: "Pre-consultation form",
    quickQuestions: "quick questions",
    thanksSummary: "Thanks! Here's your summary:",
    concern: "Concern",
    sendSummary: "Click the button below to send this summary on WhatsApp!",
    helloAssistant: "Hello! I'm the Arogya Clinic assistant.\n\nWhat is your main health concern today?",
    typeSymptoms: "Please type your symptoms:",
    symptomPlaceholder: "e.g. Stomach pain, Headache…",
    fever: "Fever",
    coldCough: "Cold Cough",
    thyroid: "Thyroid",
    others: "Others",

    // Footer
    footerDesc: "Expert healthcare professional dedicated to the wellness of the Muzaffarpur community at Arogya Clinic. MBBS (SKMCH), MD General medicine (DMCH Darbhanga).",
    navigation: "Navigation",
    aboutUs: "About Us",
    patientPortal: "Patient Portal",
    reserve: "Reserve (Dashboard)",
    clinicLocationTitle: "Arogya Clinic Location",
    morningTiming: "Morning visit timing 6 am to 9 am",
    eveningTiming: "Evening visit timing 3 pm to 6 pm",
    copyright: "© 2024 Dr. Deepak Kumar. All rights reserved.",

    // Common
    loading: "Loading...",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    yes: "Yes",
    no: "No",

    // Doctor in 10 Minutes page
    doctorIn10NavLabel: "Doctor in 10 Min",
    doctorIn10Badge: "🔴 Muzaffarpur Community Alert",
    doctorIn10HeroHeadline: "Your health can't wait for the weather to cool down.",
    doctorIn10HeroSub: "During this severe heatwave, traveling to a clinic can be dangerous. Stay safe and hydrated at home while receiving expert medical consultation via WhatsApp.",
    doctorIn10StartCTA: "Start Consultation via WhatsApp",
    doctorIn10FlatFee: "₹199 Flat Consultation Fee",
    doctorIn10AvgResponse: "~10 min avg. response",
    doctorIn10ResponseSub: "Average time to connect with Dr. Kumar today",
    doctorIn10CareTitle: "Care That Reaches You",
    doctorIn10CareSub: "Designed for Muzaffarpur's unique needs during peak summer.",
    doctorIn10WAFirst: "WhatsApp-First Approach",
    doctorIn10WAFirstDesc: "No complex apps to download. Send a 'Hi' on WhatsApp, share your symptoms via voice notes or photos, and receive a digital prescription directly in the chat.",
    doctorIn10LearnHow: "Learn how it works →",
    doctorIn10WarnTemp: "42°C+ Warning",
    doctorIn10WarnDesc: "Heat exhaustion is serious. If you feel dizzy or have a fever, consult immediately without leaving your fan or AC.",
    doctorIn10SpecTitle: "Conditions We Treat Remotely",
    doctorIn10SpecSub: "Quick, reliable advice — without stepping outside.",
    doctorIn10Fever: "Fever & Headache",
    doctorIn10Heat: "Heatstroke",
    doctorIn10Stomach: "Stomach Pain",
    doctorIn10BP: "Blood Pressure",
    doctorIn10Thyroid: "Thyroid",
    doctorIn10Cold: "Cold & Cough",
    doctorIn10ModeTitle: "Choose Your Consultation Mode",
    doctorIn10ChatMode: "💬 WhatsApp Chat",
    doctorIn10VideoMode: "📹 Video Call",
    doctorIn10ChatDesc: "Describe your symptoms via text or voice. Dr. Kumar reviews and responds with advice and a digital prescription.",
    doctorIn10VideoDesc: "Face-to-face video consultation with Dr. Kumar. Ideal for detailed examination and immediate clarity.",
    doctorIn10FeeTitle: "Transparent Fee",
    doctorIn10FeeAmount: "₹199",
    doctorIn10FeeValid: "Valid for 3 follow-up days. Our goal is accessible care, not just one-time visits.",
    doctorIn10FeeItem1: "General Health & Fever",
    doctorIn10FeeItem2: "Heatstroke Guidance",
    doctorIn10FeeItem3: "Chronic Care Management",
    doctorIn10TestTitle: "What Patients Are Saying",
    doctorIn10Test1: "\"It was too hot for my father to travel to the town centre. Dr. Kumar's WhatsApp consultation was a blessing. We got the meds within an hour.\"",
    doctorIn10Test1Author: "— Rajesh Kumar, Sakra, Muzaffarpur",
    doctorIn10Test2: "\"मेरे बच्चे को तेज बुखार था। Dr. Deepak ने 8 मिनट में WhatsApp पर पूरा इलाज बता दिया। बहुत अच्छी सेवा!\"",
    doctorIn10Test2Author: "— Sunita Devi, Kanti, Muzaffarpur",
    doctorIn10Test3: "\"Heatstroke symptoms, no way to go out. Dr. Kumar's video call saved us. Clear prescription in minutes. Highly recommended!\"",
    doctorIn10Test3Author: "— Amit Singh, Muzaffarpur City",
    doctorIn10HowTitle: "How to Consult Today",
    doctorIn10Step1Title: "Send a WhatsApp Message",
    doctorIn10Step1Desc: "Text \"Heatwave Care\" to +91 98XX XXXXX. Our coordinator will ask for basic patient details.",
    doctorIn10Step2Title: "Secure UPI Payment",
    doctorIn10Step2Desc: "Receive a secure payment link for the ₹199 fee. Pay via GPay, PhonePe, or Paytm instantly.",
    doctorIn10Step3Title: "Doctor Interaction",
    doctorIn10Step3Desc: "Dr. Deepak Kumar will call you back or start the chat consultation to review symptoms and provide guidance.",
    doctorIn10CompTitle: "Physical Clinic vs. Doctor in 10 Min",
    doctorIn10CompFeature: "Feature",
    doctorIn10CompClinic: "Physical Clinic",
    doctorIn10CompOnline: "Doctor in 10 Min",
    doctorIn10CompRow1: "Travel required",
    doctorIn10CompRow2: "Wait time",
    doctorIn10CompRow3: "Consultation fee",
    doctorIn10CompRow4: "Prescription format",
    doctorIn10CompRow5: "Safe in heatwave",
    doctorIn10FAQTitle: "Frequently Asked Questions",
    doctorIn10FAQ1Q: "Is the ₹199 consultation fee all-inclusive?",
    doctorIn10FAQ1A: "Yes! The ₹199 fee covers the initial consultation and 3 days of follow-up queries via WhatsApp. No hidden charges.",
    doctorIn10FAQ2Q: "Is the digital prescription valid at pharmacies?",
    doctorIn10FAQ2A: "Yes. Dr. Kumar's digital prescription (PDF) is valid at all pharmacies in Bihar and can be shared via WhatsApp or email.",
    doctorIn10FAQ3Q: "Who can use this service?",
    doctorIn10FAQ3A: "Anyone in Muzaffarpur and surrounding districts. Ideal for patients who cannot travel due to heatwave, mobility issues, or distance.",
    doctorIn10FAQ4Q: "Is my medical information kept private?",
    doctorIn10FAQ4A: "Absolutely. All consultations are strictly confidential. Your data is never shared with third parties.",
    doctorIn10FAQ5Q: "What if my condition is serious?",
    doctorIn10FAQ5A: "If Dr. Kumar determines your condition requires in-person care, he will immediately advise you and guide you to the nearest facility.",
    doctorIn10TrustTitle: "Trusted & Certified",
    doctorIn10Trust1: "IMA Registered",
    doctorIn10Trust2: "MCI Certified",
    doctorIn10Trust3: "Secure UPI",
    doctorIn10Trust4: "100% Confidential",
    doctorIn10Emergency: "Emergency Support",
    doctorIn10EmergencyDesc: "If you are experiencing severe chest pain, extreme breathlessness, or unconsciousness, please visit the nearest hospital emergency room immediately.",
    doctorIn10Ambulance: "🚑 Local Ambulance: 102 / 108",
  },
  hi: {
    // Navigation
    home: "होम",
    about: "परिचय",
    services: "सेवाएं",
    appointments: "अपॉइंटमेंट बुक करें",
    contact: "संपर्क करें",

    // Home Page — Hero
    welcome: "स्वागत है",
    drName: "डॉ. दीपक कुमार",
    tagline: "आपका विश्वसनीय स्वास्थ्य साथी",
    specialty: "एमबीबीएस, एमडी (जनरल मेडिसिन)",
    experience: "15+ वर्ष का अनुभव",
    bookAppointment: "अभी अपॉइंटमेंट बुक करें",
    viewServices: "हमारी सेवाएं देखें",
    location: "मुजफ्फरपुर, बिहार",
    heroDesc: "हम मधुमेह, रक्तचाप, थायरॉयड, अस्थमा, सीओपीडी और पेट के रोगों के लिए दिशानिर्देश-निर्देशित व्यापक देखभाल प्रदान करते हैं, जो आपके दीर्घकालिक कल्याण को प्राथमिकता देते हैं।",
    education: "शिक्षा",
    educationDetail: "एमबीबीएस, एसकेएमसीएच",
    specialization: "विशेषज्ञता",
    specializationDetail: "एमडी जनरल मेडिसिन, डीएमसीएच दरभंगा",

    // Home Page — Why Choose Us
    whyChooseTitle: "हमारा अभ्यास क्यों चुनें",
    whyChooseDesc: "हम अकादमिक कठोरता को रोगी-केंद्रित देखभाल के साथ जोड़ते हैं ताकि आपको मुजफ्फरपुर में सर्वोत्तम संभव चिकित्सा परिणाम मिल सकें।",
    academicExcellence: "शैक्षणिक उत्कृष्टता",
    academicExcellenceDesc: "एसकेएमसीएच से बुनियादी प्रशिक्षण और डीएमसीएच दरभंगा से उन्नत एमडी जनरल मेडिसिन विशेषज्ञता के साथ, डॉ. दीपक कुमार निजी अभ्यास में संस्थागत विशेषज्ञता लाते हैं।",
    patientFirst: "रोगी पहले",
    patientFirstDesc: "सुनने और सहानुभूति को प्राथमिकता देना। हर इलाज की योजना आपके अद्वितीय स्वास्थ्य प्रोफाइल और जीवनशैली के अनुसार तैयार की जाती है।",
    modernFacility: "आधुनिक सुविधा",
    modernFacilityDesc: "सटीक मूल्यांकन और प्रभावी प्रबंधन के लिए नवीनतम नैदानिक उपकरणों से सुसज्जित।",
    verifiedExperience: "सत्यापित अनुभव",
    verifiedExperienceDesc: "सफल रोगी परिणामों का एक सिद्ध ट्रैक रिकॉर्ड और मुजफ्फरपुर चिकित्सा समुदाय में एक विश्वसनीय नाम।",

    // Home Page — Core Services
    coreServicesTitle: "मुख्य चिकित्सा सेवाएं",
    coreServicesDesc: "आपकी दीर्घकालिक स्वास्थ्य यात्रा का समर्थन करने के लिए कई disciplines में विशेषज्ञ देखभाल।",
    generalConsultation: "सामान्य परामर्श",
    generalConsultationDesc: "व्यापक स्वास्थ्य जांच और नियमित कल्याण प्रबंधन।",
    diagnostics: "निदान",
    diagnosticsDesc: "सटीक निदान के लिए गहन प्रयोगशाला परीक्षण और नैदानिक मूल्यांकन।",
    chronicCare: "पुरानी देखभाल",
    chronicCareDesc: "मधुमेह, उच्च रक्तचाप और अधिक के लिए दीर्घकालिक प्रबंधन रणनीतियाँ।",
    emergencyAdvice: "आपातकालीन सलाह",
    emergencyAdviceDesc: "गंभीर देखभाल मार्गदर्शन और तत्काल नैदानिक हस्तक्षेप।",
    exploreServices: "सभी चिकित्सा सेवाएं देखें",

    // Home Page — CTA
    ctaTitle: "बेहतर स्वास्थ्य की ओर पहला कदम उठाएं।",
    ctaDesc: "मुजफ्फरपुर में वैयक्तिकृत चिकित्सा परामर्श के लिए आज ही अपना अपॉइंटमेंट शेड्यूल करें।",
    ctaButton: "अभी अपॉइंटमेंट बुक करें",
    phone: "9199943818",

    // About Page
    aboutTitle: "डॉ. दीपक कुमार के बारे में",
    aboutSubtitle: "स्वास्थ्य सेवा में उत्कृष्टता के प्रति समर्पित",
    aboutDesc: "तिरहुत संभाग में रोगी देखभाल में क्रांति लाने के लिए समर्पित एक प्रतिष्ठित चिकित्सा पेशेवर हैं। मुजफ्फरपुर, \"उत्तर बिहार की राजधानी\" में स्थित, वह उन्नत चिकित्सा विज्ञान और दयालु उपचार के बीच की खाई को पाटते हैं, समुदाय के स्वास्थ्य के लिए एक विश्वसनीय शरण प्रदान करते हैं।",
    yearsExp: "5+ वर्ष",
    yearsExpDesc: "बिहार में नैदानिक उत्कृष्टता और सामुदायिक सेवा का।",

    // About Page — Education
    academicFoundation: "शैक्षणिक आधार",
    mbbs: "एमबीबीएस",
    mbbsCollege: "श्री कृष्ण मेडिकल कॉलेज (एसकेएमसीएच)",
    mbbsDesc: "बिहार के प्रमुख संस्थानों में से एक में उनकी बुनियादी चिकित्सा शिक्षा पूरी की, जिससे एक मजबूत नैदानिक दृष्टिकोण विकसित हुआ।",
    md: "एमडी जनरल मेडिसिन",
    mdCollege: "दरभंगा मेडिकल कॉलेज (डीएमसीएच दरभंगा)",
    mdDesc: "विशेषज्ञ प्रशिक्षण जिसने नैदानिक सटीकता और उन्नत चिकित्सीय हस्तक्षेप में उनकी विशेषज्ञता को निखारा।",
    eliteTraining: " elite प्रशिक्षण",
    eliteTrainingDesc: "बिहार के सबसे कठोर चिकित्सा sanctuaries में शिक्षित।",

    // About Page — Community
    communityTitle: "मुजफ्फरपुर के प्रति आजीवन वचन",
    communityDesc: "मुजफ्फरपुर सिर्फ एक अभ्यास स्थल से ज्यादा है; यह घर है। आरोग्य क्लिनिक से संचालित, डॉ. दीपक कुमार की प्रतिबद्धता \"शाही लीची की भूमि\" के केंद्र तक फैली हुई है। वह स्थानीय स्वास्थ्य पहलों में गहराई से शामिल हैं, यह सुनिश्चित करते हुए कि बिहार में हर वर्ग के लिए गुणवत्तापूर्ण स्वास्थ्य सेवा सुलभ हो।",
    freeCamps: "वंचित आबादी के लिए नियमित निःशुल्क स्वास्थ्य शिविर।",
    mentorship: "स्थानीय चिकित्सा उम्मीदवारों के लिए mentorship कार्यक्रम।",
    preventiveHealth: "ग्रामीण क्षेत्रों में निवारक स्वास्थ्य शिक्षा के प्राथमिक अधिवक्ता।",

    // About Page — Milestones
    milestonesTitle: "पेशेवर मील के पत्थर",
    milestonesDesc: "नैदानिक उत्कृष्टता और अकादमिक कठोरता की एक विरासत।",
    foundation: "नींव",
    academicCommencement: "अकादमिक प्रारंभ",
    academicCommencementDesc: "एसकेएमसीएच, मुजफ्फरपुर से एमबीबीएस स्नातक।",
    specializationLabel: "विशेषज्ञता",
    advancedMedicine: "उन्नत चिकित्सा",
    advancedMedicineDesc: "प्रतिष्ठित दरभंगा मेडिकल कॉलेज से एमडी जनरल मेडिसिन प्राप्त किया।",
    establishment: "स्थापना",
    civicLeadership: "नागरिक नेतृत्व",
    civicLeadershipDesc: "मुजफ्फरपुर में सहानुभूतिपूर्ण देखभाल पर केंद्रित एक प्रमुख क्लिनिक स्थापित किया।",

    // About Page — Accreditations
    accreditationsTitle: "मान्यता और सम्मान",
    imaMember: "आईएमए सदस्य",
    imaDesc: "इंडियन मेडिकल एसोसिएशन",
    boardCertified: "बोर्ड प्रमाणित",
    boardDesc: "मेडिकल काउंसिल ऑफ इंडिया",
    excellenceAward: "उत्कृष्टता पुरस्कार",
    awardDesc: "स्टेट हेल्थ मिशन",
    fellowship: "फेलोशिप",
    fellowshipDesc: "इंटरनल मेडिसिन",

    // Services Page
    servicesHeroBadge: "रोगी-केंद्रित उत्कृष्टता",
    servicesHeroTitle: "आपके कल्याण के लिए अनुकूलित विशेष देखभाल",
    servicesHeroDesc: "आधुनिक स्वास्थ्य सेवा के लिए एक दयालु, संपादकीय दृष्टिकोण के साथ अत्याधुनिक नैदानिक उपकरणों को जोड़ने वाले व्यापक चिकित्सा समाधान का अनुभव करें।",
    clinicalServices: "नैदानिक सेवाएं",
    clinicalServicesDesc: "हमारा बहु-विषयक दृष्टिकोण सुनिश्चित करता है कि हर रोगी को केंद्रित ध्यान और एक वैयक्तिकृत इलाज रोडमैप मिले।",
    diabetesBp: "मधुमेह और रक्तचाप प्रबंधन",
    diabetesBpDesc: "मधुमेह और उच्च रक्तचाप जैसी पुरानी स्थितियों के प्रबंधन के लिए दिशानिर्देश-निर्देशित चिकित्सा उपचार। हम निरंतर निगरानी और वैयक्तिकृत चिकित्सीय योजनाएं प्रदान करते हैं ताकि आपके वाइटल संतुलित और इष्टतम रहें।",
    learnMore: "और जानें",
    endocrineCare: "एंडोक्राइन देखभाल",
    endocrineCareDesc: "थायरॉयड-संबंधी विकारों का उन्नत निदान और समग्र प्रबंधन।",
    respiratoryHealth: "श्वसन स्वास्थ्य",
    respiratoryHealthDesc: "अस्थमा, सीओपीडी और अन्य फुफ्फुसीय चुनौतियों के लिए विशेषज्ञ हस्तक्षेप।",
    abdomenDiseases: "पेट के रोग",
    abdomenDiseasesDesc: "पेट और जीआई ट्रैक्ट से संबंधित रोगों के लिए विशेषज्ञ परामर्श और इलाज की योजनाएं।",
    teleconsultation: "टेलीकंसल्टेशन",
    teleconsultationDesc: "अपने घर के आराम से दूरस्थ रूप से वैयक्तिकृत चिकित्सा सलाह और फॉलो-अप देखभाल तक पहुंचें।",
    beyondMedicine: "चिकित्सा से परे: स्वास्थ्य में भागीदारी",
    evidenceBased: "सबूत-आधारित प्रोटोकॉल",
    evidenceBasedDesc: "नवीनतम नैदानिक अनुसंधान और वैश्विक चिकित्सा मानकों में जड़ें उपचार।",
    personalizedTouch: "वैयक्तिकृत स्पर्श",
    personalizedTouchDesc: "हर रोगी अद्वितीय है। हम ऐसी चिकित्सा योजनाएं बनाते हैं जो व्यक्तिगत जीवनशैली का सम्मान करती हैं।",
    startRecovery: "स्वस्थ होने का रास्ता शुरू करें",
    startRecoveryDesc: "आज ही एक व्यापक परामर्श शेड्यूल करें और आधुनिक युग के लिए पुन:कल्पित स्वास्थ्य सेवा का अनुभव करें।",
    scheduleAppt: "अपॉइंटमेंट शेड्यूल करें",
    viewPricing: "मूल्य देखें",

    // Appointments Page
    appointmentTitle: "अपना अपॉइंटमेंट बुक करें",
    clinicLocation: "क्लिनिक का स्थान",
    address: "सक्तिधरमकटा बड़ा जगन्नाथ, गॉड फादर पब्लिक स्कूल के पास, 842004",
    phoneNumber: "फोन नंबर",
    phoneValue: "919994381893",
    operatingHours: "संचालन के घंटे",
    hoursValue: "सुबह का समय 6 बजे से 9 बजे तक\nशाम का समय 3 बजे से 6 बजे तक",
    emailAddress: "ईमेल पता",
    emailValue: "deepakkumar21121995@gmail.com",
    availableToday: "आज उपलब्ध",
    requestAppointment: "अपॉइंटमेंट का अनुरोध करें",
    appointmentRequested: "अपॉइंटमेंट का अनुरोध किया गया!",
    appointmentRequestedMsg: "हमें आपका अनुरोध प्राप्त हो गया है और हम जल्द ही आपसे संपर्क करेंगे।",
    submissionFailed: "सबमिशन विफल",
    fullName: "पूरा नाम",
    namePlaceholder: "जैसे रमेश कुमार",
    phonePlaceholder: "91 00000 00000",
    emailPlaceholder: "your@email.com",
    preferredDate: "पसंदीदा तारीख",
    preferredTime: "पसंदीदा समय स्लॉट",
    medicalConcern: "चिकित्सा चिंता",
    concernPlaceholder: "संक्षिप्त में अपनी स्वास्थ्य समस्या का वर्णन करें...",
    sendRequest: "अनुरोध भेजें",
    sending: "भेजा जा रहा है...",
    privacyPolicy: "इस फॉर्म को जमा करके, आप हमारी गोपनीयता नीति से सहमत होते हैं।",
    bookNow: "अपॉइंटमेंट बुक करें",
    confirmation: "अपॉइंटमेंट सफलतापूर्वक बुक किया गया!",
    confirmationMsg: "आपको शीघ्र ही पुष्टि कॉल प्राप्त होगी।",
    selectDate: "तारीख चुनें",
    selectTime: "समय स्लॉट चुनें",
    symptoms: "अपने लक्षणों का वर्णन करें",

    // Time Slots
    morningSlot: "सुबह (9 बजे - 12 बजे)",
    afternoonSlot: "दोपहर (2 बजे - 5 बजे)",
    eveningSlot: "शाम का क्लिनिक (8:30 बजे के बाद)",
    teleconsultSlot: "टेलीकंसल्टेशन",

    // WhatsApp Button
    whatsappChat: "व्हाट्सएप पर चैट करें",
    whatsappMsg: "नमस्ते डॉ. दीपक, मैं आपसे परामर्श करना चाहता हूं।",
    available24x7: "24x7 उपलब्ध",
    instantResponse: "त्वरित प्रतिक्रिया",

    // WhatsApp Widget
    reset: "फिर से शुरू",
    send: "भेजें",
    sendTo: "को भेजें",
    yourDetails: "आपकी जानकारी सीधे जाती है",
    preConsultForm: "पूर्व-परामर्श फॉर्म",
    quickQuestions: "त्वरित प्रश्न",
    thanksSummary: "धन्यवाद! यहाँ आपका सारांश है:",
    concern: "समस्या",
    sendSummary: "नीचे दिए गए बटन पर क्लिक करके व्हाट्सएप पर यह सारांश भेजें!",
    helloAssistant: "नमस्ते! 👋 मैं आरोग्य क्लिनिक का सहायक हूं।\n\nआज आपकी मुख्य स्वास्थ्य समस्या क्या है?",
    typeSymptoms: "कृपया अपने लक्षण टाइप करें:",
    symptomPlaceholder: "जैसे पेट दर्द, सिरदर्द…",
    fever: "बुखार",
    coldCough: "सर्दी खांसी",
    thyroid: "थायरॉयड",
    others: "अन्य",

    // Footer
    footerDesc: "मुजफ्फरपुर में आरोग्य क्लिनिक पर समुदाय के कल्याण के लिए समर्पित विशेषज्ञ स्वास्थ्य देखभाल पेशेवर। एमबीबीएस (एसकेएमसीएच), एमडी जनरल मेडिसिन (डीएमसीएच दरभंगा)।",
    navigation: "नेविगेशन",
    aboutUs: "हमारे बारे में",
    patientPortal: "रोगी पोर्टल",
    reserve: "रिजर्व (डैशबोर्ड)",
    clinicLocationTitle: "आरोग्य क्लिनिक का स्थान",
    morningTiming: "सुबह का समय 6 बजे से 9 बजे तक",
    eveningTiming: "शाम का समय 3 बजे से 6 बजे तक",
    copyright: "© 2024 डॉ. दीपक कुमार। सर्वाधिकार सुरक्षित।",

    // Common
    loading: "लोड हो रहा है...",
    submit: "सबमिट करें",
    cancel: "रद्द करें",
    save: "सहेजें",
    close: "बंद करें",
    yes: "हाँ",
    no: "नहीं",

    // Doctor in 10 Minutes page
    doctorIn10NavLabel: "10 मिनट में डॉक्टर",
    doctorIn10Badge: "🔴 मुजफ्फरपुर सामुदायिक अलर्ट",
    doctorIn10HeroHeadline: "आपका स्वास्थ्य मौसम के ठंडा होने का इंतजार नहीं कर सकता।",
    doctorIn10HeroSub: "इस भीषण गर्मी में क्लिनिक तक जाना खतरनाक हो सकता है। घर पर सुरक्षित रहें और WhatsApp के जरिए विशेषज्ञ चिकित्सा परामर्श लें।",
    doctorIn10StartCTA: "WhatsApp पर परामर्श शुरू करें",
    doctorIn10FlatFee: "₹199 फ्लैट परामर्श शुल्क",
    doctorIn10AvgResponse: "~10 मिनट औसत प्रतिक्रिया",
    doctorIn10ResponseSub: "आज Dr. Kumar से जुड़ने का औसत समय",
    doctorIn10CareTitle: "देखभाल जो आप तक पहुँचे",
    doctorIn10CareSub: "मुजफ्फरपुर की विशिष्ट जरूरतों के लिए, गर्मी के चरम मौसम में।",
    doctorIn10WAFirst: "WhatsApp-फर्स्ट अप्रोच",
    doctorIn10WAFirstDesc: "कोई जटिल ऐप डाउनलोड नहीं। WhatsApp पर 'Hi' भेजें, वॉयस नोट या फोटो से अपने लक्षण साझा करें, और सीधे चैट में डिजिटल प्रिस्क्रिप्शन पाएं।",
    doctorIn10LearnHow: "जानें यह कैसे काम करता है →",
    doctorIn10WarnTemp: "42°C+ चेतावनी",
    doctorIn10WarnDesc: "हीट एग्जॉस्शन गंभीर है। अगर आपको चक्कर आए या बुखार हो, तो अपने पंखे या AC से बाहर निकले बिना तुरंत परामर्श लें।",
    doctorIn10SpecTitle: "हम दूर से इन बीमारियों का इलाज करते हैं",
    doctorIn10SpecSub: "बाहर कदम रखे बिना — त्वरित, विश्वसनीय सलाह।",
    doctorIn10Fever: "बुखार और सिरदर्द",
    doctorIn10Heat: "लू (हीटस्ट्रोक)",
    doctorIn10Stomach: "पेट दर्द",
    doctorIn10BP: "ब्लड प्रेशर",
    doctorIn10Thyroid: "थायरॉयड",
    doctorIn10Cold: "सर्दी और खांसी",
    doctorIn10ModeTitle: "परामर्श का तरीका चुनें",
    doctorIn10ChatMode: "💬 WhatsApp चैट",
    doctorIn10VideoMode: "📹 वीडियो कॉल",
    doctorIn10ChatDesc: "टेक्स्ट या वॉयस के जरिए लक्षण बताएं। Dr. Kumar समीक्षा करके सलाह और डिजिटल प्रिस्क्रिप्शन के साथ जवाब देंगे।",
    doctorIn10VideoDesc: "Dr. Kumar के साथ आमने-सामने वीडियो परामर्श। विस्तृत जांच और तुरंत स्पष्टता के लिए आदर्श।",
    doctorIn10FeeTitle: "पारदर्शी शुल्क",
    doctorIn10FeeAmount: "₹199",
    doctorIn10FeeValid: "3 फॉलो-अप दिनों के लिए वैध। हमारा लक्ष्य सुलभ देखभाल है, न केवल एक बार का दौरा।",
    doctorIn10FeeItem1: "सामान्य स्वास्थ्य और बुखार",
    doctorIn10FeeItem2: "हीटस्ट्रोक मार्गदर्शन",
    doctorIn10FeeItem3: "पुरानी बीमारी प्रबंधन",
    doctorIn10TestTitle: "मरीज क्या कह रहे हैं",
    doctorIn10Test1: "\"मेरे पिताजी के लिए शहर के केंद्र तक जाना बहुत गर्म था। Dr. Kumar का WhatsApp परामर्श वरदान था। हमें एक घंटे में दवाएं मिल गईं।\"",
    doctorIn10Test1Author: "— राजेश कुमार, सकरा, मुजफ्फरपुर",
    doctorIn10Test2: "\"मेरे बच्चे को तेज बुखार था। Dr. Deepak ने 8 मिनट में WhatsApp पर पूरा इलाज बता दिया। बहुत अच्छी सेवा!\"",
    doctorIn10Test2Author: "— सुनीता देवी, कांटी, मुजफ्फरपुर",
    doctorIn10Test3: "\"लू के लक्षण थे, बाहर निकलने का कोई रास्ता नहीं। Dr. Kumar की वीडियो कॉल ने बचा लिया। मिनटों में स्पष्ट प्रिस्क्रिप्शन। अत्यधिक अनुशंसित!\"",
    doctorIn10Test3Author: "— अमित सिंह, मुजफ्फरपुर शहर",
    doctorIn10HowTitle: "आज परामर्श कैसे लें",
    doctorIn10Step1Title: "एक WhatsApp संदेश भेजें",
    doctorIn10Step1Desc: "\"Heatwave Care\" लिखकर +91 98XX XXXXX पर भेजें। हमारे समन्वयक बुनियादी मरीज विवरण मांगेंगे।",
    doctorIn10Step2Title: "सुरक्षित UPI भुगतान",
    doctorIn10Step2Desc: "₹199 शुल्क के लिए एक सुरक्षित भुगतान लिंक प्राप्त करें। तुरंत GPay, PhonePe या Paytm से भुगतान करें।",
    doctorIn10Step3Title: "डॉक्टर से बातचीत",
    doctorIn10Step3Desc: "Dr. Deepak Kumar आपको कॉल करेंगे या लक्षणों की समीक्षा और मार्गदर्शन देने के लिए चैट परामर्श शुरू करेंगे।",
    doctorIn10CompTitle: "फिजिकल क्लिनिक बनाम 10 मिनट में डॉक्टर",
    doctorIn10CompFeature: "सुविधा",
    doctorIn10CompClinic: "फिजिकल क्लिनिक",
    doctorIn10CompOnline: "10 मिनट में डॉक्टर",
    doctorIn10CompRow1: "यात्रा आवश्यक",
    doctorIn10CompRow2: "प्रतीक्षा समय",
    doctorIn10CompRow3: "परामर्श शुल्क",
    doctorIn10CompRow4: "प्रिस्क्रिप्शन प्रारूप",
    doctorIn10CompRow5: "गर्मी में सुरक्षित",
    doctorIn10FAQTitle: "अक्सर पूछे जाने वाले सवाल",
    doctorIn10FAQ1Q: "क्या ₹199 का परामर्श शुल्क सब कुछ शामिल करता है?",
    doctorIn10FAQ1A: "हाँ! ₹199 की फीस में प्रारंभिक परामर्श और WhatsApp पर 3 दिनों की फॉलो-अप क्वेरी शामिल हैं। कोई छिपा हुआ शुल्क नहीं।",
    doctorIn10FAQ2Q: "क्या डिजिटल प्रिस्क्रिप्शन फार्मेसी में मान्य है?",
    doctorIn10FAQ2A: "हाँ। Dr. Kumar का डिजिटल प्रिस्क्रिप्शन (PDF) बिहार की सभी फार्मेसियों में मान्य है और WhatsApp या ईमेल से साझा किया जा सकता है।",
    doctorIn10FAQ3Q: "इस सेवा का उपयोग कौन कर सकता है?",
    doctorIn10FAQ3A: "मुजफ्फरपुर और आसपास के जिलों में कोई भी। उन मरीजों के लिए आदर्श जो गर्मी, गतिशीलता समस्याओं या दूरी के कारण यात्रा नहीं कर सकते।",
    doctorIn10FAQ4Q: "क्या मेरी चिकित्सा जानकारी निजी रहती है?",
    doctorIn10FAQ4A: "बिल्कुल। सभी परामर्श पूरी तरह गोपनीय हैं। आपका डेटा कभी तीसरे पक्ष के साथ साझा नहीं किया जाता।",
    doctorIn10FAQ5Q: "अगर मेरी स्थिति गंभीर हो तो क्या होगा?",
    doctorIn10FAQ5A: "यदि Dr. Kumar यह निर्धारित करते हैं कि आपकी स्थिति के लिए व्यक्तिगत देखभाल आवश्यक है, तो वे तुरंत सलाह देंगे और निकटतम सुविधा तक मार्गदर्शन करेंगे।",
    doctorIn10TrustTitle: "विश्वसनीय और प्रमाणित",
    doctorIn10Trust1: "IMA पंजीकृत",
    doctorIn10Trust2: "MCI प्रमाणित",
    doctorIn10Trust3: "सुरक्षित UPI",
    doctorIn10Trust4: "100% गोपनीय",
    doctorIn10Emergency: "आपातकालीन सहायता",
    doctorIn10EmergencyDesc: "अगर आपको गंभीर सीने में दर्द, अत्यधिक सांस फूलना या बेहोशी हो रही है, तो कृपया तुरंत निकटतम अस्पताल के इमरजेंसी विभाग में जाएं।",
    doctorIn10Ambulance: "🚑 स्थानीय एम्बुलेंस: 102 / 108",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('doctor_profile_language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('doctor_profile_language', language);
  }, [language]);

  const t = (key) => translations[language][key] || key;
  const toggleLanguage = () => setLanguage(prev => prev === 'en' ? 'hi' : 'en');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
